# Generated by Django 2.0.6 on 2018-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upploud', '0002_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
