# Generated by Django 2.0.6 on 2018-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upploud', '0003_auto_20180622_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
