# Generated by Django 2.0.6 on 2018-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upploud', '0004_auto_20180622_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='upploud.Tag'),
        ),
    ]
